### PR TITLE
update lib for mongodb 3.x changes

### PR DESCRIPTION
**Pull request by ebourmalo**

### CODE REVIEW

**Comment by daffl** [comment]
Any news on this? @scttnlsn If you're looking for help maintaining the project we're happy to help out.

**Comment by scttnlsn** [comment]
Yeah, help maintaining this would be most welcome!  I don't think this has anything to do with this PR but I'm getting a test failure on this branch:

```
Uncaught MongoError: cursor killed or timed out
      at queryCallback (node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:88:23)
      at Callbacks.emit (node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
      at null.messageHandler (node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
      at Socket.<anonymous> (node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

I'd like to fix up the tests and setup Travis CI so PRs can be reviewed quicker without regressions.

**Comment by daffl** [comment]
I'll have a look. I can also set up the CI and release scripts that I usually use.

**Comment by daffl** [comment]
@scttnlsn I got the tests passing and added a Travis CI configuration script and NPM script to quickly  make a release by running `npm run release:<major|minor|patch>`.
The project probably needs to be enabled at https://travis-ci.org/profile.

**Comment by scttnlsn** [comment]
@daffl Awesome- thank you!

**Pull request merged**
